### ISSUE TITLE
Session Storage

### ISSUE THREAD

**Issue by Botsmarksblocket** [Zenty/TEAMUNDEFINED_KIOSK#18]
Vi ska använda Session Storage för att spara de items som användaren väljer att lägga till i kundvagnen.
Sessionen ska tömmas efter checkout.
Det ska gå att manuellt ta bort produkt items från kundvagnen.

**Comment by Zenty** [comment]
Hur går det med Session Storage? 
Kom ihåg att uppdatera din egna bransch medans du arbetar!
