### ISSUE TITLE
Skriv en README fil

### ISSUE THREAD

**Issue by Botsmarksblocket** [Zenty/TEAMUNDEFINED_KIOSK#19]
Skriva en detaljerad README fil som innehåller alla gruppmedlemmar, projekt beskrivning, projekt mål etc.

**Comment by Zenty** [comment]
Hur går det med README filen, Raoof?

**Comment by Zenty** [comment]
Ser bra ut!
Ska det stå "##Funktioner" eller blev det ett fel med headingen?
