### ISSUE TITLE
Cart-ikon - responsiv styling

### ISSUE THREAD

**Issue by kirosabe** [Zenty/TEAMUNDEFINED_KIOSK#23]
Det ser inte bra ut vid mobilvy och behöver fixas för förbättrad synlighet och användbarhet.

![icon_mobile](https://github.com/user-attachments/assets/ec5da161-65dc-4dac-8f2b-75e62d18d2a6)

Lösning: Lägg till media queries för att justera storlek mm på mindre skärmar.

**Comment by kirosabe** [comment]
Insåg nu att jag hade zoom på 50% och att det kan va därför det såg lurt ut. När jag ändrar till 100% ser det ok ut men kan någon annan kika också?

**Comment by kirosabe** [comment]
Kanske hade varit bra med en fallbacklösning om det är någon webbläsare som  inte stödjer svg dock?

**Comment by Zenty** [comment]
Tycker det ser bra ut, det end problemet jag ser är att det inte riktigt känns som att kundvagnen är i mitten av cirkeln. Kanske en liten padding-left skulle kunna få den att se mer centrerad ut?

Om du kan fixa en fallbackslösning till svg blir det grymt, men inte ett krav då jag tror att svg har stöd i alla moderna webbläsare. Så titta bara på fallbackslösningar om du har tid & är intresserad!

**Comment by kirosabe** [comment]
Håller med dig, iallafall när jag kikar på hjulen. Var jättesvårt att få det att se bra ut, har uppenbarligen inget bra ögonmått. Du får gärna kika igen! Här: #37
