### ISSUE TITLE
Skapa Dryck & Snacks Sektion

### ISSUE THREAD

**Issue by Zenty** [Zenty/TEAMUNDEFINED_KIOSK#29]
Sektionerna ska kunna fällas upp och ner.

**Comment by Zenty** [comment]
Ser bra ut!
Jag tror det vore bra om vi såg till att sektionerna som standard visade produkterna utan att man behöver fälla ner dem. 
Sen hade det nog varit bra om vi hade kunnat placera Dryck sektionen först och sedan Snacks.
Annars är det bara designen vi behöver titta på!

**Comment by Botsmarksblocket** [comment]
Produkterna är nu nedfällda vid page load. Har bytt plats på snacka- och dryckessektionen.

**Comment by Zenty** [comment]
Kanon!
