### ISSUE TITLE
Designa Dryck & Snacks Sektion

### ISSUE THREAD

**Issue by Zenty** [Zenty/TEAMUNDEFINED_KIOSK#34]
Designa våra sektioner så att de ser snygga ut.

**Comment by Zenty** [comment]
Bra jobbat.
Ser att sektionerna är öppna som standard nu. Men känns som det är något konstigt som händer när man refreshar sidan, dryck & snack sektionerna hanteras olika, snacks sektionen är helt öppen från början när man refreshar men dryck sektionen öppnas som om man precis tryckt för att öppna den.

**Comment by Botsmarksblocket** [comment]
![Image](https://github.com/user-attachments/assets/a40ff068-88b8-4fbd-a314-6ae58b98fc2f)
Hur det ser ut när sektionerna är stängda

**Comment by Botsmarksblocket** [comment]
![Image](https://github.com/user-attachments/assets/65cffea1-9cd0-4ec1-bf0b-9f72e3f48a53)
Och när de är öppna.

Vet inte riktigt hur jag ska få det att se bra ut. Har experimenterat med att göra headern mer färgrann än knapparna och vice versa men ser alltid lite off ut.

**Comment by Botsmarksblocket** [comment]
![Image](https://github.com/user-attachments/assets/f625259f-1d60-46d4-8665-95f72b7fc571)

Och när de är öppna.

Vet inte riktigt hur jag ska få det att se bra ut. Har försökt att göra headern mer färgrann än knapparna och vice versa men det ser alltid lite "off" ut.

**Comment by Zenty** [comment]
Ja. Kanske vore en bra idé att behålla headern som svart/mörk grå och ta bort färg från bakgrunden bakom produkterna. Tror att det blir lite för många gradients.

**Comment by Botsmarksblocket** [comment]
![Image](https://github.com/user-attachments/assets/376bd904-88f8-4344-8f92-393e2d3f4f67)
Collapsed.

![Image](https://github.com/user-attachments/assets/41768cd3-2f29-40c0-bcf4-752337928056)
Expanderad.

Ändrade headern till väldigt mörkgrå och gjorde färgen bakom produkterna ljusare.

**Comment by Zenty** [comment]
Tycker färgerna för sektionerna ser bra ut nu.
